name: CI
on:
  - push
  - pull_request
jobs:
  test:
    name: Node.js ${{ matrix.node-version }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 14
    steps:
      - uses: codecov/codecov-action@v3.1.1
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install all dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Codecov
        uses: codecov/codecov-action@v3.1.1
